language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
install:
  - echo python version
  - echo $TRAVIS_PYTHON_VERSION
  - chmod u+x core_dependency_installer.sh
  - source core_dependency_installer.sh $TRAVIS_PYTHON_VERSION
  - pip install -r optional-requirements.txt
  - pip install coverage
  - pip install nose
script:
  - "nosetests -xv plotly/tests --with-coverage --cover-package=plotly"
